name: text_interpolate
version: 0.0.2
author: Filip Hracek <filip.hracek@gmail.com>
description: Minimal library for random interpolation between two Strings. To be used for 'animation' - tweening between texts.
homepage: https://github.com/filiph/text_interpolate
