name: text_interpolate
version: 0.0.1
author: Filip Hracek <filip.hracek@gmail.com>
description: Minimal library for random interpolation between two Strings. To be used for 'animation' - tweening between texts.
